DROP TABLE Contestant CASCADE CONSTRAINTS;

DROP TABLE Judge CASCADE CONSTRAINTS;

DROP TABLE Round CASCADE CONSTRAINTS;

DROP TABLE Enrollment CASCADE CONSTRAINTS;

DROP TABLE Evaluation CASCADE CONSTRAINTS;

DROP TABLE EvaluationScore CASCADE CONSTRAINTS;

DROP TABLE Notice CASCADE CONSTRAINTS;

